"""
LLM Classifier

Uses Ollama to classify an academic question based on
the prompt generated by ContextBuilder.

Responsibilities
----------------
1. Send prompt to Ollama.
2. Parse the JSON response.
3. Validate the response.
4. Return structured classification.

This module does NOT:
- retrieve documents
- build context
- build prompts
- calculate confidence
"""

import json
import logging
import re

import ollama

from app.config import MODEL_NAME

logger = logging.getLogger(__name__)


class LLMClassifier:
    """
    Handles interaction with the local Ollama model.
    """

    # ======================================================
    # Public API
    # ======================================================

    def classify(
        self,
        prompt: str
    ) -> dict:
        """
        Classify an academic question using a prepared prompt.

        Parameters
        ----------
        prompt : str
            Prompt generated by ContextBuilder.

        Returns
        -------
        dict
            Structured classification.
        """

        response = self._call_model(prompt)

        return self._validate_response(response)

    # ======================================================
    # Ollama Call
    # ======================================================

    def _call_model(
        self,
        prompt: str
    ) -> dict:

        try:

            response = ollama.chat(

                model=MODEL_NAME,

                messages=[

                    {
                        "role": "system",

                        "content": (
                            "You are an Academic Doubt "
                            "Classification Engine.\n\n"

                            "Return ONLY valid JSON.\n"

                            "Do NOT explain.\n"

                            "Do NOT think aloud.\n"

                            "Do NOT use markdown.\n"

                            "Do NOT use code fences."
                        )

                    },

                    {
                        "role": "user",

                        "content": prompt
                    }

                ]

            )

            text = response["message"]["content"]

            logger.debug(
                "Raw LLM Response:\n%s",
                text
            )

            text = self._clean_response(text)

            return json.loads(text)

        except Exception as error:

            logger.exception(error)

            return {}

    # ======================================================
    # Response Cleaning
    # ======================================================

    @staticmethod
    def _clean_response(
        text: str
    ) -> str:
        """
        Remove markdown, thinking blocks,
        and surrounding text.
        """

        text = text.replace(
            "```json",
            ""
        )

        text = text.replace(
            "```",
            ""
        )

        text = re.sub(
            r"<think>.*?</think>",
            "",
            text,
            flags=re.DOTALL
        )

        text = text.strip()

        start = text.find("{")

        end = text.rfind("}")

        if start != -1 and end != -1:

            text = text[start:end + 1]

        return text

    # ======================================================
    # Validation
    # ======================================================

    @staticmethod
    def _validate_response(
        result: dict
    ) -> dict:
        """
        Ensure every required field exists.
        """

        default = {

            "subject": "Unknown",

            "topic": "Unknown",

            "subtopic": "Unknown",

            "difficulty": "Unknown"

        }

        if not isinstance(
            result,
            dict
        ):
            return default

        for key, value in default.items():

            result.setdefault(
                key,
                value
            )

        allowed = {

            "Easy",

            "Medium",

            "Hard"

        }

        if result["difficulty"] not in allowed:

            result["difficulty"] = "Unknown"

        return result


# ======================================================
# Singleton
# ======================================================

llm_classifier = LLMClassifier()


# ======================================================
# Module Test
# ======================================================

if __name__ == "__main__":

    sample_prompt = """
Context

MapReduce is a distributed programming
model used in Hadoop.

Student Question

What is MapReduce?

Return only JSON.
"""

    result = llm_classifier.classify(
        sample_prompt
    )

    print(
        json.dumps(
            result,
            indent=4
        )
    )